name: zichen
port: 8022
user_srv:
  name: 'user_srv'
jwt:
  key: 'O7ZA7RE!=be7'
sms:
  key: 'LTAI5tA8amT2P5TiYB73XTos'
  secrect: 'W278E8lwasu1IrK0iZSKPlTKAnuHTe'
  expire: 900
redis:
  host: '127.0.0.1'
  port: 6379
consul:

  host: '127.0.0.1'
  port: 8500